### ISSUE TITLE
Addition of Python and Node version badges in Readme

### ISSUE THREAD

**Issue by shubhank-saxena** [developer-student-club-thapar/officialWebsite#100]
Looks cool! Dynamically should pick up!

**Comment by mk-singhal** [comment]
Hi there,
I would like to work on it, please assign it to me.

**Comment by priyanshsaxena24** [comment]
Hey, can i take this issue?.. @jaskeerat789 ....I am new to Open-Source Contribution and would love to start by contributing here.

**Comment by jaskeerat789** [comment]
@deathzombie I am sorry but i have to assign this task to @mk-singhal  since he reached out first.

**Comment by mk-singhal** [comment]
Can you help me with the file (url/name) from where the badge should fetch data...

**Comment by raghavTinker** [comment]
can you assign this issue to me.

Thanks

**Comment by jaskeerat789** [comment]
> Can you help me with the file (url/name) from where the badge should fetch data...

the badges need to go into readme file on root of the project

**Comment by bughunter9** [comment]
@jaskeerat789 @shubhank-saxena  As a PR has not been merged till now , Can I also take on this one ??

**Comment by mk-singhal** [comment]
Sorry, I'm bit busy and don't think would get enough time to complete it....

**Comment by priyanshsaxena24** [comment]
@jaskeerat789 by the order of preference, can I get this issue assigned?

**Comment by jsparmani** [comment]
Done in #328
