### ISSUE TITLE
fix home page overflow

### ISSUE THREAD

**Issue by jsparmani** [developer-student-club-thapar/officialWebsite#106]
![image](https://user-images.githubusercontent.com/41769747/82050762-56b39980-96d6-11ea-8441-109987a033e8.png)

**Comment by animesh-007** [comment]
This looks good? 
<img width="414" alt="Screen Shot 2020-06-23 at 8 31 29 AM" src="https://user-images.githubusercontent.com/53366877/85356189-f6611480-b52b-11ea-8cca-adc950029013.png">

**Comment by aniketbiswas21** [comment]
Fixed :smile:
