### ISSUE TITLE
UI Correction bottom segment social links

### ISSUE THREAD

**Issue by jsparmani** [developer-student-club-thapar/officialWebsite#12]
![image](https://user-images.githubusercontent.com/41769747/73609637-b7bad400-45f5-11ea-92d1-f03e08bef90d.png)
The placement of the bottom segment of social links changes on redirection to the home page back.
This is when it first opens

**Comment by jsparmani** [comment]
![image](https://user-images.githubusercontent.com/41769747/73609650-e042ce00-45f5-11ea-91ce-3d0437dbb178.png)
This is after navigating back to it.

**Comment by kush-daga** [comment]
Its linked to #2 somehow!

**Comment by kush-daga** [comment]
Done with contact form correction #2
