### ISSUE TITLE
Fix environments to show consistent lint check across

### ISSUE THREAD

**Issue by shubhank-saxena** [developer-student-club-thapar/officialWebsite#13]
Right now you see that Travis tests of linting is failing. But it must be passing local systems as my pre-commit is allwoing. 
Fix it

**Comment by jsparmani** [comment]
@shubhank-saxena i feel using tox to carry out python linting tests could work. Let me know if shall I proceed with this soln

**Comment by shubhank-saxena** [comment]
> @shubhank-saxena i feel using tox to carry out python linting tests could work. Let me know if shall I proceed with this soln

Yes. A good approach. But not very sure how this will change and effect the difference between the environments

**Comment by jsparmani** [comment]
Okay, i will proceed with a few options
