### ISSUE TITLE
pyc Cache File are for System only shouldn't be pushed to repo

### ISSUE THREAD

**Issue by AroraShreshth** [developer-student-club-thapar/officialWebsite#19]
The Current .gitignore isn't updated for Django updations

**Comment by animesh-007** [comment]
@AroraShreshth  If this issue is resolved should we close this issue now?

**Comment by AroraShreshth** [comment]
Your choice honestly 😃. Things are working without that tok

**Comment by animesh-007** [comment]
@shubhank-saxena Can we close this issue for now?

**Comment by shubhank-saxena** [comment]
Yes!
