### ISSUE TITLE
Archive Team Feature

### ISSUE THREAD

**Issue by jsparmani** [developer-student-club-thapar/officialWebsite#252]
Providing function to archive teams year wise like 2019-20, 2020-21 and so on.
Needs backend as well as UI changes.

@Saurav-Shrivastav and @aniketbiswas21 to head for these changes along with the team.

**Comment by jaskeerat789** [comment]
Any updates on this? @jsparmani  are we planing to make a admin control panel for this?

**Comment by jsparmani** [comment]
> Any updates on this? @jsparmani  are we planing to make a admin control panel for this?

A PR on this will be merged by today if everything goes well

**Comment by jaskeerat789** [comment]
@jsparmani  can you explain what exactly we are doing in this?

**Comment by jsparmani** [comment]
As written in the description,  it will help us to maintain and display teams and leads academic year wise
@jaskeerat789

**Comment by jsparmani** [comment]
Done
