### ISSUE TITLE
Remove Chatbot

### ISSUE THREAD

**Issue by shubhank-saxena** [developer-student-club-thapar/officialWebsite#255]
Over-engineered feature. Don't need it imo. @jsparmani your views?

**Comment by jsparmani** [comment]
Yeah, @shubhank-saxena I was also planning the same. Not serving any purpose as of now. Can be removed.

**Comment by jsparmani** [comment]
Whoever is working on this, please refer to the following [link](https://github.com/developer-student-club-thapar/officialWebsite/commit/a1f5facdb72e33dff7259ba6be7a8faf1ea563f1) diff for the appropriate changes.

**Comment by jsparmani** [comment]
@aniketbiswas21 @animesh-007 Please consider this issue urgent and take actions to remove it ASAP.

**Comment by paras55** [comment]
> 
> 
> Over-engineered feature. Don't need it imo. @jsparmani your views?

Sure , Can be removed. 
Can we used further if there is a need :-)

**Comment by aniketbiswas21** [comment]
@jsparmani Working on it right away.
