### ISSUE TITLE
Remove "Join us on Slack" Button

### ISSUE THREAD

**Issue by jaskeerat789** [developer-student-club-thapar/officialWebsite#279]
**Is your feature request related to a problem? Please describe.**
Need to remove the `Join us on Slack` button form the home page.
![image](https://user-images.githubusercontent.com/38110126/94342025-d9a51300-002b-11eb-9251-bf9501e654cd.png)

**Describe alternatives you've considered**
No Alternative

**Comment by crs2here** [comment]
I can pick this up

**Comment by crs2here** [comment]
do you want the text above removed as well?

**Comment by crs2here** [comment]
I'm using python3.8 and I'm getting a pre commit errors. Like this 

```
    Installing collected packages: appdirs, typing-extensions, mypy-extensions, click, regex, pathspec, toml, typed-ast, black
        Running setup.py install for regex: started
        Running setup.py install for regex: finished with status 'error'
```

**Comment by jaskeerat789** [comment]
@jsparmani pls look into this pre commit error

**Comment by jaskeerat789** [comment]
@crs2here make a pr in October, this issues is for hacktoberfest

**Comment by rohan2734** [comment]
@jaskeerat789   Hey i would like to work on this issue can you assign me this issue

**Comment by crs2here** [comment]
@jaskeerat789 sorry I got too excited about hacktober I'll wait till then. I also want to mention this project is organized very well.

**Comment by crs2here** [comment]
@jaskeerat789 @jsparmani I figured out how to commit by following this article https://opensource.com/article/19/5/python-3-default-mac. I had two versions of python on my system so I had to change the default to 3.8. I'll submit the PR in October. Thank you for your help

**Comment by jsparmani** [comment]
That's great @crs2here 🚀

**Comment by shivambhatia5432** [comment]
Hey I tried solving this issue without conflicts at PR #305

**Comment by jaskeerat789** [comment]
@shivambhatia5432 thanks a lot for your efforts and the PR but we had to wait till October before we could assign the task to anyone. Since @crs2here reached us first, i am assigning him this task.

**Comment by shivambhatia5432** [comment]
No issues man will my PR be considered in Hacktoberfest even after that?

**Comment by jsparmani** [comment]
> No issues man will my PR be considered in Hacktoberfest even after that?

Yeah, your PR is still open with us, so it will be considered.

Waiting for @crs2here to open a PR for the same otherwise you can work upon it further.

Thanks!

**Comment by crs2here** [comment]
@jsparmani I will submit it now thank you

**Comment by jsparmani** [comment]
Done in #308
