### ISSUE TITLE
Click on nav-bar logo and name to go back to home page.

### ISSUE THREAD

**Issue by jaskeerat789** [developer-student-club-thapar/officialWebsite#280]
**Is your feature request related to a problem? Please describe.**
click on nav-bar logo and name to go back to home page. One should be able to go back `/#` when he clicks on the logo and name in the nav-bar, irrespective of the fact that he is on which page.

**Describe the solution you'd like**
a simple <a> tag could work but i would prefer using the react-router implementation.

**Comment by sandeepbanoula** [comment]
I will give it a try.

**Comment by jaskeerat789** [comment]
@sandeepbanoula this issue is tagged as hacktoberfest, make a pr in october to be a part of it.... mean while register for our event [here](https://organize.mlh.io/participants/events/4053-hacktoberfest-with-dsc-tiet-patiala)

**Comment by sandeepbanoula** [comment]
I have implemented this but on hover, this style was applied. Can I remove it?
![Annotation 2020-09-26 224239](https://user-images.githubusercontent.com/65235940/94346352-c1dc8780-0049-11eb-88ba-a38a2fba235f.png)

**Comment by sandeepbanoula** [comment]
> @sandeepbanoula this issue is tagged as hacktoberfest, make a pr in October to be a part of it.... mean while register for our event [here](https://organize.mlh.io/participants/events/4053-hacktoberfest-with-dsc-tiet-patiala)

Okay. I think it was started because my Hacktoberfest dashboard was showing a 0/4 pull request. I will make a PR in October. Thanks and also I am a first timer so please guide me.

**Comment by rohan2734** [comment]
Hi is this issue closed or assigned to someone? or else i would like to work on it.

**Comment by karans5004** [comment]
Hi @jaskeerat789 / admins, 
I have fixed the issue, need to submit PR, 
Pl assign the issue to me.
Thanks.

**Comment by jaskeerat789** [comment]
I am assigning this Task to @sandeepbanoula since he was the first one to reach. Hope to see a solution soon sandeep

**Comment by sandeepbanoula** [comment]
> I am assigning this Task to @sandeepbanoula since he was the first one to reach. Hope to see a solution soon Sandeep

Thanks, @jaskeerat789 for assigning this issue to me. I have submitted a PR, guide me if any further changes are needed.
