### ISSUE TITLE
no action on clicking the cards

### ISSUE THREAD

**Issue by jaskeerat789** [developer-student-club-thapar/officialWebsite#281]
**Describe the bug**
The card at home page are clickable but they do nothing... we should attach routing to them as well.

**To Reproduce**
1. go to the [website](https://dsctiet.tech/#/) 
2. scroll down as shown in this [image](https://user-images.githubusercontent.com/38110126/94346665-ca35c200-004b-11eb-9fa7-3457a251009d.png)
3. click on the cards shown on the page.

**Expected behavior**
show take you to the respective section.

**Screenshots**
![image](https://user-images.githubusercontent.com/38110126/94346676-e33e7300-004b-11eb-882b-1becd5d5a484.png)

**Comment by ShubhamSood1406** [comment]
Can I work on this?

**Comment by Jeremiahiro** [comment]
I can get no this

**Comment by swastikchugh** [comment]
Hey @jaskeerat789, I would like to fix this.

**Comment by jaskeerat789** [comment]
Guys these issues are marked as hacktoberfest and will be available to solve from October. Meanwhile you can register for hacktoberfest at [this link](http://dsctiet.xyz/hacktoberfest).

**Comment by ShubhamSood1406** [comment]
@jaskeerat789 I already registered on that, so can I work on this?

**Comment by ShubhamSood1406** [comment]
> Guys these issues are marked as hacktoberfest and will be available to solve from October. Meanwhile you can register for hacktoberfest at [this link](http://dsctiet.xyz/hacktoberfest).

@jaskeerat789 I had already registered on the Hacktoberfest, please assign it to me so that I can start working on this issue.

**Comment by skamp91** [comment]
Hey :) Is it possible that I also work on this Issue?

GoodRegards :)

**Comment by ShubhamSood1406** [comment]
@jaskeerat789 At least assign this issue to someone.

**Comment by jaskeerat789** [comment]
@ShubhamSood1406 sorry for being late but i had to wait till 1st of october. I am assigning this to you since you were the first one to reach out.

**Comment by jsparmani** [comment]
Done in #325
