### ISSUE TITLE
Typo's at the the end of readme file. 

### ISSUE THREAD

**Issue by akgupta-47** [developer-student-club-thapar/officialWebsite#289]
There are typo's at the end of `README.md` file.

**Comment by akgupta-47** [comment]
@hactoberfest

**Comment by kboshold** [comment]
@akgupta-47 Does the PR contain all the types you meant. If not, which ones need to be added?

**Comment by akgupta-47** [comment]
There was one or two really small typing errors in the end of readme.md file

**Comment by Utkarshn10** [comment]
@akgupta-47 I have fixed the typo at the end of the readme.md i.e(adding space between) contributers and specification and making a small change in the line after that i.e I changed  "Contributions of any kind welcome!" to "Contributions of any kind are welcomed!". 

I am a beginner to Open-source therefore guide me and specify any other changes that should be done in the readme.md file.
