### ISSUE TITLE
Change dark mode slider

### ISSUE THREAD

**Issue by animesh-007** [developer-student-club-thapar/officialWebsite#313]
**Is your feature request related to a problem? Please describe.**
Currently, the Slider of the dark mode is too simple.
**Describe the solution you'd like**
Would like to have one like this [link](https://codepen.io/maximakymenko/pen/mdbpeXm)
**Describe alternatives you've considered**
Anything which is like in the provided link.

**Comment by deepankkartikey** [comment]
@shubhank-saxena @animesh-007 
I would like to pick this up, please assign it to me.

**Comment by shubhank-saxena** [comment]
Sure @deepank120896 . Go ahead!

**Comment by Aashishkushwaha** [comment]
Hi @animesh-007  Can I work on this ? If yes, please assign this to me.

**Comment by animesh-007** [comment]
Ok sure. Since no PR is been raised until now.

**Comment by animesh-007** [comment]
Solved in #315.
