### ISSUE TITLE
Apply dark mode on map

### ISSUE THREAD

**Issue by animesh-007** [developer-student-club-thapar/officialWebsite#318]
**Is your feature request related to a problem? Please describe.**
Currently, the map on the Home page remains in light mode even in dark mode.

**Describe the solution you'd like**
It would be nice to change into dark mode when dark mode is switched on.

**Describe alternatives you've considered**
Any solution which converts the map to a dark theme like in dark mode.

**Comment by bobluppes** [comment]
Hey, I can work on this if you assign it to me!

**Comment by jagveer-loky** [comment]
I can give a helpful hands on this :)

**Comment by animesh-007** [comment]
> Hey, I can work on this if you assign it to me!

Sure.

**Comment by animesh-007** [comment]
> I can give a helpful hands on this :)

Sorry, @jagveer-loky. As @bobluppes asked first so I assigned him for now.

**Comment by jagveer-loky** [comment]
No worries, I will seek another one. Keep in touch

**Comment by animesh-007** [comment]
@bobluppes are you working on this?

**Comment by bobluppes** [comment]
Hey, @animesh-007. Sorry but I didn't see the assignment and am working on another project atm. Maybe @jagveer-loky still has time to look at this?

**Comment by animesh-007** [comment]
> Hey, @animesh-007. Sorry but I didn't see the assignment and am working on another project atm. Maybe @jagveer-loky still has time to look at this?

ok cool.

**Comment by animesh-007** [comment]
@jagveer-loky would you like to work on this?

**Comment by jagveer-loky** [comment]
Sorry, i'd jumped on another one.

**Comment by jsparmani** [comment]
Done in #325
