### ISSUE TITLE
Improve Event Card

### ISSUE THREAD

**Issue by jsparmani** [developer-student-club-thapar/officialWebsite#333]
**Is your feature request related to a problem? Please describe.**
Yeah, visibility of info on event card

**Describe the solution you'd like**
Needs to be more visually appealing and legible.

**Describe alternatives you've considered**
Anything good can be done

**Additional context**
![image](https://user-images.githubusercontent.com/41769747/95714453-df366600-0c85-11eb-87c4-1c4d4f8e8fca.png)

**Comment by NUMBART** [comment]
@jsparmani, I would like to work on this

**Comment by jsparmani** [comment]
Sure, @NUMBART assigning it to you. Any ETA on this?

**Comment by NUMBART** [comment]
I think I will be able to do this by 15th. This will be my first time. Wanted to clarify we would like the event heading and details text to be styled better right.

**Comment by jsparmani** [comment]
> I think I will be able to do this by 15th. This will be my first time. Wanted to clarify we would like the event heading and details text to be styled better right.

Yeah good! 
Yeah, event heading and details need to be styled better. Also, a good looking button instead of the `Link` text could be done.
![image](https://user-images.githubusercontent.com/41769747/95717027-f414f880-0c89-11eb-945d-4b0b2d7db54f.png)

**Comment by NUMBART** [comment]
@jsparmani just completed this. Let me know if I should change anything else to this.
Edit: Forgot the title in the earlier image
![image](https://user-images.githubusercontent.com/26141133/96001318-874e5980-0e55-11eb-9069-5fbcd20f02ac.png)

**Comment by jsparmani** [comment]
Looks good @NUMBART. We can have a PR for this.

**Comment by NUMBART** [comment]
I will raise one. There is one problem though I accidentally used yarn instead of npm.
Should I just remove the yarn.lock file and then run npm install and submit the PR?

**Comment by jsparmani** [comment]
Hey @NUMBART not to worry! If you carefully see, this project also uses `yarn` and not `npm`. 
Feel free to open the PR.
Did you mean the other way round?

**Comment by NUMBART** [comment]
Actually I originally installed using yarn. Then I thought I was doing it wrong so reinstalled using npm(which is now causing one of the fails). I will see to this and install lint too pass the tests.

**Comment by jsparmani** [comment]
Done
