### ISSUE TITLE
Send Proposal Button on Sponsorship Card

### ISSUE THREAD

**Issue by jsparmani** [developer-student-club-thapar/officialWebsite#334]
**Is your feature request related to a problem? Please describe.**
Yeah, the button is non functional.

**Describe the solution you'd like**
Link the button to send us a mail at dsc.tiet@gmail.com

**Describe alternatives you've considered**
No alternative.

**Additional context**
![image](https://user-images.githubusercontent.com/41769747/95714868-7ac7d680-0c86-11eb-8b68-fc8c73327b72.png)

**Comment by SaravgiYash** [comment]
Hi, @jsparmani I would like to work on this issue.

**Comment by jsparmani** [comment]
Sure @Yashs911. Assigned it to you!

**Comment by SaravgiYash** [comment]
@jsparmani I have created a PR
