### ISSUE TITLE
Correct Home Page Typo

### ISSUE THREAD

**Issue by jsparmani** [developer-student-club-thapar/officialWebsite#335]
**Is your feature request related to a problem? Please describe.**
Incorrect Spelling. Minor changes

**Describe the solution you'd like**
Change the main home page text from "Developer Students Club" to "Developer Student Clubs" (Club should be plural and not Student)

**Describe alternatives you've considered**
N/A

**Additional context**
![image](https://user-images.githubusercontent.com/41769747/95715048-d003e800-0c86-11eb-893a-db3041a5d29d.png)
Make the changes here.

**Comment by stevenjburrows** [comment]
I will fix this for you if you want to assign it to me

**Comment by jsparmani** [comment]
Sure, @stevenjburrows assigning it to you!

**Comment by SaravgiYash** [comment]
@jsparmani Can I create a PR for this issue?

**Comment by stevenjburrows** [comment]
> @jsparmani Can I create a PR for this issue?

I have already created the pr for it

**Comment by SaravgiYash** [comment]
> I have already created the pr for it

@stevenjburrows oh okay

**Comment by jsparmani** [comment]
Done in #336
