### ISSUE TITLE
Change Website Title

### ISSUE THREAD

**Issue by jsparmani** [developer-student-club-thapar/officialWebsite#339]
**Is your feature request related to a problem? Please describe.**
Yeah. The website title needs to be updated.

**Describe the solution you'd like**
Change Title from "DSC Website" to "DSC TIET | Google Developers | Patiala"

**Describe alternatives you've considered**
N/A

**Additional context**
![image](https://user-images.githubusercontent.com/41769747/95865464-5a7e4180-0d84-11eb-87dc-ef584a56b0a0.png)

**Comment by liamortiz** [comment]
On it !

**Comment by liamortiz** [comment]
Completed 👍
