### ISSUE TITLE
Click on button triggers event in parent container too

### ISSUE THREAD

**Issue by NUMBART** [developer-student-club-thapar/officialWebsite#344]
**Describe the bug**
Clicking on 'Learn More' button in Events cards also propagates click to StyledCard

**To Reproduce**
Navigate to Events page. First click on one of the cards anywhere apart from the card's button. Only the description pops up, next click on the button. The description pops up and the page loads the link referred to by the button

**Expected behavior**
Clicking on the button should not be triggering the description popup.

**Screenshots**
![Screenshot from 2020-10-15 21-43-01](https://user-images.githubusercontent.com/26141133/96157198-a0c3d400-0f2f-11eb-9d69-dd0d8858e035.png)
Clicking the Hacktoberfest 2019-20 event card 'Learn More' button has triggered the description as well as the link to start loading

**Desktop (please complete the following information):**

- OS: Ubuntu
- Browser: Firefox

**Comment by sprakash57** [comment]
I would like to work on the issue. is it still available?

**Comment by DivjyotSingh** [comment]
I would like to work on this issue @jsparmani

**Comment by jsparmani** [comment]
As @sprakash57 requested earlier, I would like to give him a chance first. @sprakash57 Please let me know if you still want to work on this else I can assign this to @DivjyotSingh .

**Comment by sprakash57** [comment]
@jsparmani you can assign it to @DivjyotSingh. Currently i am working on other issues.

**Comment by jsparmani** [comment]
@DivjyotSingh Assigned.
