### ISSUE TITLE
Team Page Issue

### ISSUE THREAD

**Issue by aniketbiswas21** [developer-student-club-thapar/officialWebsite#39]
All the members listed as Jaskeerat Singh Randhawa in IOT team and various other places.
![dscissue](https://user-images.githubusercontent.com/51146347/76697478-c2b95780-66bd-11ea-99c0-028483367c45.png)

**Comment by shubhank-saxena** [comment]
@aniketbiswas21 thank you for this issue. Currently, our website is in development, so to check for the biggest possible layouts, we used Jaskeerat's name everywhere!
