### ISSUE TITLE
About us button

### ISSUE THREAD

**Issue by shubhank-saxena** [developer-student-club-thapar/officialWebsite#4]
About us button should be renamed to Code of Conduct and this document should be linked to it
https://docs.google.com/document/d/1bbpf78aMSH2ntSZEWR09Q05OVDHFp6IoFlVHtcvC0eQ/edit?usp=sharing

**Comment by kush-daga** [comment]
maybe add a link to this in about us section?

**Comment by shubhank-saxena** [comment]
@kush-daga that can be displayed on the main page. Re-direction not needed. Code of Conduct is important

**Comment by jsparmani** [comment]
Changed the about button to code of conduct as about already present in navbar.
4b92140b58967bb20a8fe40256986117585c4aba
@shubhank-saxena confirm once!
