### ISSUE TITLE
Teams Page by Year and corresponding API

### ISSUE THREAD

**Issue by aniketbiswas21** [developer-student-club-thapar/officialWebsite#493]
**Is your feature request related to a problem? Please describe.**
We can have a tab section on the teams page, which helps us navigate through the DSC team over the years.

**Describe the solution you'd like**
A tab with years, which on select changes the team and displays the DSC team of that particular year.

**Describe alternatives you've considered**
None

**Additional context**
Apart from the frontend work, the above change also requires additions in the backend side(possibly storing the year corresponding to each member and then exposing an API that fetches all the members by year)

**Comment by raghavTinker** [comment]
- [x] Backend API database must be storing the positions of the members for each year
- [x] Create an API endpoint for listing years and an endpoint for each year to get member details
- [x] Year-wise listing of members required in frontend
