### ISSUE TITLE
Join Our Slack

### ISSUE THREAD

**Issue by shubhank-saxena** [developer-student-club-thapar/officialWebsite#5]
Join our Slack button should link to the Slack Workspace using the link - 
https://join.slack.com/t/dscthapar-gspatiala/shared_invite/enQtNzU2MzA2MjcxNzkyLTkwNDRiNWMzYjUzYjNjYjM0M2JhMDgwOTI3MGQwYWU1NzNlNGMxZGVhNzk0MGZiYTI5YzgwZDhiMTk1MjE4M2M

**Comment by kush-daga** [comment]
Done

**Comment by jsparmani** [comment]
@kush-daga I guess the linking is still left on the main home page button.

**Comment by kush-daga** [comment]
Its working @jsparmani

**Comment by kush-daga** [comment]
Where is the issue?

**Comment by jsparmani** [comment]
![image](https://user-images.githubusercontent.com/41769747/73609587-3ebb7c80-45f5-11ea-899e-91fae9e4dce4.png)
On this button

**Comment by shubhank-saxena** [comment]
@jsparmani remove it from the navbar!

**Comment by kush-daga** [comment]
Ugh lol ok

**Comment by shubhank-saxena** [comment]
XD

**Comment by jsparmani** [comment]
Issue resolved in 8c0a8b567c70a8383219c36debd4fefcf965ec6a.
Closing now.
