### ISSUE TITLE
Anchor Player does not show controls

### ISSUE THREAD

**Issue by shubhank-saxena** [developer-student-club-thapar/officialWebsite#534]
**Describe the bug**
Hello team.
The anchor player (bottom of the screen on the podcast page) has a weird alignment, hiding the player.

**To Reproduce**

1. Go to https://dsctiet.tech/#/podcast

**Screenshots**
![Screenshot 2022-04-27 at 8 42 44 PM (2)](https://user-images.githubusercontent.com/29003047/165551703-fe84b9bf-fc2a-4d22-9e02-20354e566539.png)

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: Brave
- Version: Version 1.37.116 Chromium: 100.0.4896.127 (Official Build) (arm64)](https://brave.com/latest/)

**Comment by yash22arora** [comment]
Fixed with commit #871. Please confirm if it works fine now, @shubhank-saxena

**Comment by shubhank-saxena** [comment]
Looks good! Thank you

**Comment by yash22arora** [comment]
Great!
