### ISSUE TITLE
Nav Bar Edit

### ISSUE THREAD

**Issue by shubhank-saxena** [developer-student-club-thapar/officialWebsite#6]
Meet our team button should link to Teams page. So, remove the teams tab from nav bar

**Comment by kush-daga** [comment]
I guess it can be in both places? since navigating to team pages fro other sections can still be possible via navbar

**Comment by shubhank-saxena** [comment]
Yes. But given that our page is quite simple to navigate I think we can have just one. Rest, the team can have a discussion on this!
