### ISSUE TITLE
Add join us on Slack button in Readme

### ISSUE THREAD

**Issue by shubhank-saxena** [developer-student-club-thapar/officialWebsite#65]
This is the link that is to be used! Make sure it's adjacent to the builds button!
https://dscthapar-gspatiala.slack.com/join/shared_invite/enQtNzU2MzA2MjcxNzkyLTkwNDRiNWMzYjUzYjNjYjM0M2JhMDgwOTI3MGQwYWU1NzNlNGMxZGVhNzk0MGZiYTI5YzgwZDhiMTk1MjE4M2M

**Comment by jsparmani** [comment]
Great 🚀
