### ISSUE TITLE
Shifting to poetry

### ISSUE THREAD

**Issue by shubhank-saxena** [developer-student-club-thapar/officialWebsite#66]
We already have an existing pyproject.toml file in your codebase. We should ideally shift to poetry instead of conventional requirements.txt installation system!

**Comment by animesh-007** [comment]
https://github.com/python-poetry/poetry
@shubhank-saxena I was reading this but I was not able to figure out which files I should change to use pyproject.toml.

**Comment by shubhank-saxena** [comment]
> https://github.com/python-poetry/poetry
> @shubhank-saxena I was reading this but I was not able to figure out which files I should change to use pyproject.toml.

https://stackoverflow.com/questions/60251799/how-to-start-a-new-django-project-using-poetry

**Comment by animesh-007** [comment]
So I think we need to make changes in contribution.md and remove requirement.txt

**Comment by shubhank-saxena** [comment]
> So I think we need to make changes in contribution.md and remove requirement.txt

Yes!

**Comment by animesh-007** [comment]
Okay I will try to do that with readme.me one

**Comment by animesh-007** [comment]
<img width="694" alt="Screen Shot 2020-05-10 at 11 55 21 PM" src="https://user-images.githubusercontent.com/53366877/81507278-db3e9a80-9319-11ea-9a70-bdbd6da9d067.png">

I have some doubt
Will all these steps be made on the route directory? And is there any changes with the names of the files?

**Comment by shubhank-saxena** [comment]
> <img alt="Screen Shot 2020-05-10 at 11 55 21 PM" width="694" src="https://user-images.githubusercontent.com/53366877/81507278-db3e9a80-9319-11ea-9a70-bdbd6da9d067.png">
> 
> I have some doubt
> Will all these steps be made on the route directory? And is there any changes with the names of the files?

I don't think there is no need of changing file names. We already have a pyproject.toml

**Comment by animesh-007** [comment]
> > <img alt="Screen Shot 2020-05-10 at 11 55 21 PM" width="694" src="https://user-images.githubusercontent.com/53366877/81507278-db3e9a80-9319-11ea-9a70-bdbd6da9d067.png">
> > I have some doubt
> > Will all these steps be made on the route directory? And is there any changes with the names of the files?
> 
> I don't think there is no need of changing file names. We already have a pyproject.toml

I was actually asking for djangodemo  and django-admin.py😅

**Comment by shubhank-saxena** [comment]
I am not sure about the instructions. This already has implemented poetry. Kindly refer to this
https://github.com/developer-student-club-thapar/buying_selling_devops/blob/master/CONTRIBUTION.md
