### ISSUE TITLE
Welcome bot configuration

### ISSUE THREAD

**Issue by shubhank-saxena** [developer-student-club-thapar/officialWebsite#75]
https://probot.github.io/apps/welcome/
This will help us to welcome new contributors in a better way! 
Do ask about the messages that are to be put in the configuration file!

**Comment by animesh-007** [comment]
I tried to go through the link but I was unable to find anything to do any configuration.
Can you provide any link?

**Comment by shubhank-saxena** [comment]
> I tried to go through the link but I was unable to find anything to do any configuration.
> Can you provide any link?

There is instructions below in the same link. Check it out!
![Screenshot from 2020-05-12 13-12-55](https://user-images.githubusercontent.com/29003047/81653381-5a36ee80-9452-11ea-8800-c0a8a5a4c5b4.png)

**Comment by jsparmani** [comment]
@shubhank-saxena There's also a [github action](https://github.com/actions/starter-workflows/blob/master/automation/greetings.yml) available for the same. Check this out, we can integrate this as it would be easier.

**Comment by jsparmani** [comment]
Okay, I think a PR is on it's way, let's keep it this way

**Comment by shubhank-saxena** [comment]
> @shubhank-saxena There's also a [github action](https://github.com/actions/starter-workflows/blob/master/automation/greetings.yml) available for the same. Check this out, we can integrate this as it would be easier.

This works on that basis only!
