### ISSUE TITLE
Shift the static assets on Amazon S3 Bucket

### ISSUE THREAD

**Issue by shubhank-saxena** [developer-student-club-thapar/officialWebsite#78]
@jsparmani can you help any interested reviewer with this? If no one comes around, would like you to take it up. Also, share the link of the article in the comment here!

**Comment by jsparmani** [comment]
> @jsparmani can you help any interested reviewer with this? If no one comes around, would like you to take it up. Also, share the link of the article in the comment here!

Yupp, would take it up if nobody comes up

**Comment by jsparmani** [comment]
This [link](https://testdriven.io/blog/storing-django-static-and-media-files-on-amazon-s3/) needs to be followed
