### ISSUE TITLE
Setup static files in GCP Bucket

### ISSUE THREAD

**Issue by shubhank-saxena** [developer-student-club-thapar/officialWebsite#79]
Really need to give a thought on this! We intent to shift all our static assets to GCP bucket!

**Comment by jsparmani** [comment]
These are a few resources:
- [Medium Article](https://medium.com/@umeshsaruk/upload-to-google-cloud-storage-using-django-storages-72ddec2f0d05)
- [django-storages Documentation](https://django-storages.readthedocs.io/en/latest/backends/gcloud.html)

**Comment by jsparmani** [comment]
Done
